In [10]:
import numpy as np
import pandas as pd
students = np.random.randint(50,101,size=(50,5))
stu = pd.DataFrame(students,
             columns=['國文','英文','數學','地理','歷史'],
             index=[f'第{i}號'for i in range(1,51)])
stu

       國文  英文  數學   地理  歷史
第1號    62  91  94   73  64
第2號    94  61  62   54  92
第3號    51  79  86   50  80
第4號    75  95  80   62  60
第5號    51  64  66   66  63
第6號    77  62  90   87  92
第7號    91  69  80  100  87
第8號    85  76  72   88  90
第9號    69  55  66   88  62
第10號   68  71  75   55  57
第11號   85  86  78   80  87
第12號   84  85  78   88  84
第13號   59  66  98   99  81
第14號  100  94  55   65  91
第15號   55  57  67   61  58
第16號   86  62  63   74  87
第17號   57  71  75   66  81
第18號   77  88  54   56  57
第19號   83  70  91   91  61
第20號   77  65  97   59  95
第21號   78  51  53   53  91
第22號   94  82  68   67  61
第23號   93  69  69   95  69
第24號  100  73  85   81  72
第25號   59  69  79   99  77
第26號   88  98  58   75  97
第27號   84  98  63   55  95
第28號   66  65  74   60  96
第29號   71  65  91   65  61
第30號   56  65  59   60  75
第31號   76  94  63   56  81
第32號   71  61  94   90  57
第33號   81  53  80   53  55
第34號   78  98  85   59  83
第35號   97  79  88   56  62
第36號   62  68  53   72  81
第37號   61  54  91   69  61
第38號   75  56  74   70  60
第39號   88  84  69   92  62
第40號   58  50  65   85  96
第41號   81  66  86   78  66
第42號   79  80  69   70  63
第43號   79  71  70   64  90
第44號   86  82  54   66  96
第45號   77  89  71   94  76
第46號   99  90  91   91  66
第47號   61  77  75   57  58
第48號   61  64  88   75  88
第49號   88  78  66   75  91
第50號   66  56  86   78  77

In [11]:
#Serise
chinese_serises = stu['國文']
chinese_serises

第1號      62
第2號      94
第3號      51
第4號      75
第5號      51
第6號      77
第7號      91
第8號      85
第9號      69
第10號     68
第11號     85
第12號     84
第13號     59
第14號    100
第15號     55
第16號     86
第17號     57
第18號     77
第19號     83
第20號     77
第21號     78
第22號     94
第23號     93
第24號    100
第25號     59
第26號     88
第27號     84
第28號     66
第29號     71
第30號     56
第31號     76
第32號     71
第33號     81
第34號     78
第35號     97
第36號     62
第37號     61
第38號     75
第39號     88
第40號     58
第41號     81
第42號     79
第43號     79
第44號     86
第45號     77
第46號     99
第47號     61
第48號     61
第49號     88
第50號     66
Name: 國文, dtype: int64

In [12]:
chinese_serises['第49號'] #第49號國文的成績

np.int64(88)

In [13]:
chinese_serises[['第49號', '第50號']] #第49號和第50號的國文成績

第49號    88
第50號    66
Name: 國文, dtype: int64

In [14]:
#第1號的學生
stu.loc['第1號']

國文    62
英文    91
數學    94
地理    73
歷史    64
Name: 第1號, dtype: int64

In [15]:
#第1號和第10號的學生
stu.loc[['第1號', '第10號']]

      國文  英文  數學  地理  歷史
第1號   62  91  94  73  64
第10號  68  71  75  55  57

In [18]:
#前5個學生
stu.iloc[:5]
#後5個學生
stu.iloc[-5:]

      國文  英文  數學  地理  歷史
第46號  99  90  91  91  66
第47號  61  77  75  57  58
第48號  61  64  88  75  88
第49號  88  78  66  75  91
第50號  66  56  86  78  77